name: Deploy FTP focca.dev.br

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy site estático
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          server-dir: ${{ secrets.REMOTEDIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env